version: '3.8'
services:
  web:
    depends_on:
      - db
    ports:
      - '443:80'
    build:
      context: .
      dockerfile: Application/Dockerfile
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
